---
# tasks file for ucsdlib.ffmpeg
# Install latest stable ffmpeg

- name: Make Secure, Temporary Directory
  command: mktemp -d "/tmp/ansible.XXXXXX"
  register: ffmpeg_mktemp
  notify: Remove Temporary Directory

- name: Set Temp Directory Name
  set_fact:
    ffmpeg_temp_directory: '{{ ffmpeg_mktemp.stdout | default(ffmpeg_temp_directory_default) }}'

- name: Download ffmpeg Index
  get_url:
    url: '{{ ffmpeg_homepage }}'
    dest: '{{ ffmpeg_temp_directory }}'

# Ugly screen scraping hack
- name: Get Current Version Number
  command: 'grep release: {{ ffmpeg_temp_directory }}/index.html'
  register: ffmpeg_get_version

# Uglier screen scraping hack, with --check hack grafted in
- name: Set Current Version
  set_fact:
    ffmpeg_actual_version: '{{ (ffmpeg_version == "release") | ternary( ffmpeg_get_version.stdout|default("unknown")|regex_replace(".*: ",""), ffmpeg_version ) }}'

- name: Download ffmpeg
  unarchive:
    src: '{{ ffmpeg_homepage }}/releases/ffmpeg-{{ ffmpeg_actual_version }}-64bit-static.tar.xz'
    #remote_src: yes # requires Ansible 2.2
    copy: no # Remove for Ansible 2.2
    dest: '{{ ffmpeg_install }}'
    creates: '{{ ffmpeg_install }}/ffmpeg-{{ ffmpeg_actual_version}}-64bit-static'
  environment:
    '{{ ffmpeg_webproxy | default ({}) }}'

- name: Set Default Symlink
  file:
    path: '{{ ffmpeg_install }}/ffmpeg'
    src: ffmpeg-{{ ffmpeg_actual_version }}-64bit-static
    state: link
  ignore_errors: '{{ ansible_check_mode }}'

- name: Ensure Compatibility Directory Exists
  file:
    path: '{{ ffmpeg_compatibility }}'
    state: directory

- name: Set Compatibility Symlink
  file:
    path: '{{ ffmpeg_compatibility }}/{{ item }}'
    src: '{{ ffmpeg_install }}/ffmpeg/{{ item }}'
    state: link
  ignore_errors: '{{ ansible_check_mode }}'
  with_items:
    - ffmpeg
